export interface carouselData {
    bannerId_1: string | any,
    slideTitle_1: string | any,
    slideDes_1: string | any,
    imageSrc_1: string | any,
    imageAlt_1: string | any,
    bannerId_2: string | any,
    slideTitle_2: string | any,
    slideDes_2: string | any,
    imageSrc_2: string | any,
    imageAlt_2: string | any,
    bannerId_3: string | any,
    slideTitle_3: string | any,
    slideDes_3: string | any,
    imageSrc_3: string | any,
    imageAlt_3: string | any,
}